Added a sidebar in the Region template
Solution-locale/solutionlocale.ca pull request #49
Opened 2020-03-31 19:35 UTC by Mullion21

- New visual for categories listing
- Mobile support

The front page visual has changed a little bit since it's using the same template and "for now" it doesn't need a sidebar.

2020-03-31 21:55 UTC, acrilex1 approved these changes

2020-04-01 15:50 UTC, jpmurray requested changes

2020-04-01 15:50 UTC, jpmurray commented on app/Http/Controllers/PublicController.php
> +        $categories = Category::where('parent_id', '=', null)->get();
Je pense que `Utils` existe plus? Je trouve nul part les fichiers 🤔

2020-04-01 18:27 UTC, jpmurray approved these changes

2022-02-20 14:39 UTC, closed without merging